default: &default
  :queues:
    - searchkick

development:
  <<: *default
  :concurrency: 5
  :pidfile: tmp/pids/sidekiq.pid

staging:
  <<: *default
  :concurrency: 10

production:
  <<: *default
  :concurrency: 20