default: &default
  :queues:
    - searchkick

development: &development
  <<: *default
  :concurrency: 5
  :pidfile: tmp/pids/sidekiq.pid

staging: &staging
  <<: *default
  :concurrency: 10

production: &production
  <<: *default
  :concurrency: 20